version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
  test:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run: npm test
